### PR TITLE
Fix lnd v0.12.0-beta compatibility, combine #142 and #185

### LINKED ISSUE #8: accounts: renew option
We should give users an option to renew an account that's about to expire, or has already expired.

### LINKED ISSUE #39: Create account expiry field is vague
When creating an account using ordered flags (`llm accounts new [command options] amt expiry`), it's not clear if `expiry` is `expiry_height` or `expiry_blocks`. After testing, I see that it is `expiry_height`, but that's not immediately obvious from the help displayed. 

Minor nit, I think it would be better to have `expiry_blocks` as the ordered flag. I'm more likely to remember that 1008 blocks is around one week and multiply from there pretty easily in my head. With `expiry_height`, I have to first go find the current block height, then do that same math to add onto it. I'm lazy, so help me save a few seconds.

### LINKED ISSUE #160: accounts: default value for expiration
We should have a default value for `expiry_blocks` so users don't need to decide on an expiration date. With account renewal the expiration date becomes less important. 

```
$ pool accounts new --amt=50000000
Balance: 50,000,000 sats
Expiration: 4320 blocks (~30 days)
To change the expiration pass either expiry_blocks or expiry_height
Create account? (Y/n): 
{
   ...
}
```

Default value: `12960 (~90 days)`

### PR DESCRIPTION
**Pull request by guggero**
This PR fixes compatibility with `lnd v0.12.0-beta.rc3` and later.

It also contains the full commit list of #142 and #185. As soon as the server is deployed to mainnet, this PR can be merged and the other two can be closed.

Fixes #8.
Fixes #39.
Fixes #160.

### CODE REVIEW

**Review by wpaulino — APPROVED** [review]

File: rpcserver.go [hunk 1]
```diff
@@ -1586,7 +1586,16 @@ func (s *rpcServer) sendSignBatch(batch *order.Batch, sigs order.BatchSignature,
 		switch chanInfo.Version {
 		case chanbackup.TweaklessCommitVersion:
 			channelType = poolrpc.ChannelType_TWEAKLESS
-		case chanbackup.AnchorsCommitVersion:
+
+		// The AnchorsCommitVersion was never widely deployed (at least
```
Comment (halseth) [inline rpcserver.go:1590]: 👍

**Review by halseth — APPROVED** [review]
